dkmur/Stats

config.ini.example
settings.run
sql_cron/pokemon_daily.sql.default
sql_cron/pokemon_hourly.sql.default

added:
- possibility to clear more MAD tables detect, location, status (pokemon_daily.sql)
- clear Stats table depending on RPL (add to config.ini)

Fix some stuff

---

Log.txt
otherStuff.sh
progs/atv_sw_overview.sh
progs/gmail.sh
progs/ipadresses.sh
progs/temperature_details.sh
sql/atv_sw_overview.sql
sql/gmail.sql
sql/ipadresses.sql
sql/temperature_details.sql
stats.sh

new menu options require https://github.com/dkmur/ATVdetails

Atv details

---

settings.run
sql_cron/15_worker.sql.default
sql_cron/pokemon_hourly.sql.default

make sure to execute settings.run

adapt to MAD pr877 table change

---

sql/atv_sw_overview.sql

added arch to ATVdetails and adapted Stats accaordingly

add Architecture

---

README.md
procedures.sql.default
settings.run
sql_cron/pokemon_daily.sql.default
tables.sql.default

git pull and execute settings.run

handle large chunks of data more efficiently

---

README.md
default_files/tables.sql.default
settings.run

won't require area definition but instead will create are World and pull all defined origins from MAD at setup

Add quick setup

---

default_files/01_stats_kpi.json.default
default_files/02_stats_network_area.json.default
default_files/03_stats_network_area_ex.json.default
default_files/04_stats_worker.json.default
default_files/11_stats_atvdetails_combined.json.default
default_files/12_stats_atvdetails_combined_ex.json.default
default_files/30_mon_stuff.json.default
default_files/month.sh.default
settings.run

- grafana should respect given timeline, most grafana reports updated
- add mon_stuff grafana report 100iv/0iv/shiny scanned
- optimze pokemon history table after moving it at end of month

Improve some stuff

---

default_files/1440_area.sql.default
default_files/15_area.sql.default
default_files/60_area.sql.default

Collation crap

---

cron_files/daily.sh
cron_files/weekly.sh
default_files/crontab.txt.default

pull + settings.run + crontab update

Optimize weekly

---

README.md
default_files/01_stats_kpi.json.default
default_files/02_stats_network_area.json.default
default_files/03_stats_network_area_ex.json.default
default_files/04_stats_worker.json.default
default_files/10080_worker.sql.default
default_files/1440_worker.sql.default
default_files/15_worker.sql.default
default_files/60_worker.sql.default
default_files/crontab.txt.default
default_files/tables.sql.default

missingProtoMinute = every minute check lastProtoDateTime < now() - interval 1 minute and step the counter if true
- git pull
- execute settings.run
- update crontab with content of crontab.txt located in Stats home
- update/re-import grafana templates 01until 04

add missingProtoMinute 

---

default_files/02_stats_network_area.json.default
default_files/03_stats_network_area_ex.json.default
default_files/04_stats_worker.json.default
default_files/1440_worker.sql.default

Fix daily worker stats
added teleport/walk time to templates 02/03/04
git pull, execute settings.run and re-import the 3 templates

Fix + template update

---

README.md
default_files/1440_area.sql.default
default_files/15_area.sql.default
default_files/15_worker.sql.default
default_files/60_area.sql.default
default_files/crontab.txt.default
default_files/tables.sql.default
settings.run

changing to Stats to utf8mb4_unicode_ci to be alligned with MAD.
git pull, execute settings.run and update crontab
in case of error on executing setting.run because of wrong collation for some MAD tables, try commands provided that should fix it.

change collation to utf8mb4_unicode_ci for Stats

---

default_files/06_nearby_fenced.json.default

variable for datasource is missing when importing

variable for datasource

---

README.md

This time with a signed commit.
Hope github likes me this time.

Add processing of logs to readme

---

cron_files/1440_remaining.sh
default_files/config.ini.example

Gym to stop

---

default_files/14_device_stability.json.default
settings.run

to update:
- git pull
- execute setting.run
- import new templates 14 (temperature) and 15

add device stability template

---

scripts/job_executor.sh
scripts/job_executor_inclPause.sh
scripts/pause_all_google_devices.sh
scripts/pause_all_ptc_devices.sh
scripts/pause_noproto_google_devices.sh
scripts/pause_noproto_ptc_devices.sh
scripts/unpause_batch_ptc_devices_exit.sh
scripts/unpause_google_devices.sh
scripts/unpause_ptc_devices.sh

change folder

---

justATVdetail.run
justATVdetail.txt

seperate install script for those that want to run ATVdetails but not full Stats

Just atvdetails

---

scripts/pause_all_google_devices.sh
scripts/pause_all_ptc_devices.sh
scripts/pause_noproto_google_devices.sh
scripts/pause_noproto_ptc_devices.sh

fix scripts, whoops

---

cron_files/1440_remaining.sh
default_files/60_worker.sql.default
default_files/config.ini.example
scripts/pause_all_google_devices.sh
scripts/pause_all_ptc_devices.sh
scripts/pause_noproto_google_devices.sh
scripts/pause_noproto_ptc_devices.sh
scripts/unpause_batch_ptc_devices_exit.sh
scripts/unpause_google_devices.sh
scripts/unpause_ptc_devices.sh

to update: pull + execute settings.run

vMAD cleanup

---

scripts/pause_all_google_devices.sh
scripts/pause_noproto_google_devices.sh
scripts/unpause_google_devices.sh

adjust google scripts, logintype NULL is google
to update: just pull

none is google

---

default_files/15_worker.sql.default

faster worker processing
